In [1]:
import M
import sklearn.metrics
import pandas as pd
from sklearn.linear_model import LogisticRegression

model = M.Model('healthcare-dataset-stroke-data.csv', 'stroke')
model.get_data()

In [2]:
# presenting the data after processing
model.x_data

,age,hypertension,heart_disease,avg_glucose_level,bmi,smoking_status,gender_Female,gender_Male,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban
0,0.816895,0.0,1.0,0.801265,0.301260,0.666667,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.975586,0.0,1.0,0.234512,0.254296,0.333333,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.597168,0.0,0.0,0.536008,0.276060,1.000000,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.963379,1.0,0.0,0.549349,0.156930,0.333333,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.987793,0.0,0.0,0.605161,0.214204,0.666667,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4903,0.157715,0.0,0.0,0.221402,0.095074,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4904,0.987793,0.0,0.0,0.323516,0.340206,0.333333,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4905,0.426270,0.0,0.0,0.128658,0.232532,0.333333,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4906,0.621582,0.0,0.0,0.513203,0.175258,0.666667,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4907,0.536133,0.0,0.0,0.139230,0.182131,0.000000,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [3]:
x_train, x_test, y_train, y_test = model.split_data(model.x_data.to_numpy(),model.y_data.to_numpy())

In [4]:
# simply use Logestic Regression 
lr = LogisticRegression(max_iter=3000).fit(x_train, y_train)
y_pred = lr.predict(x_test)

# produce confusion matrix of the model
pd.DataFrame(sklearn.metrics.confusion_matrix(y_test, y_pred))

     0  1
0  470  0
1   21  0

From the confusion matrix we can see that the model predict that all patients don't have stroke.

Because there are much more patients without stroke in real data, so although all predict values are 0,the model has quite good accuracy_score(0.957). However it has very bad precision and recall score(0.0), therefore we have to choose f1_score instead of accuracy to see whether the model is good.

Unfortunately f1 score is quite low (0.0), so it means Logistic Regression with default parameter is not a good choice, so in notebook2 we will choose different models with different parameters to see which one has the largest f1 score and can be used to predict whether a patient has stroke.